apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::147997135309:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-4xV7YyIQlfRH
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - test
      userarn: arn:aws:iam::147997135309:user/test
      username: test
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-08T04:38:52Z"
  name: aws-auth
  namespace: kube-system
  uid: 25d3443f-0725-4df6-abe0-54fc3430a5fd
